metadata:
  labels:
    pipeline: jenkinsfile
spec:
  containers:
    - name: 'wild'
      image: scalastic/wild
      command:
        - cat
      tty: true
      resources:
        requests:
          cpu: "0.1"
          memory: "128Mi"
        limits:
          cpu: "0.5"
          memory: "512Mi"