credentials:
  system:
    domainCredentials:
      - credentials:
          - string:
              description: kubernetes-jenkins-token
              id: kubernetes-jenkins-token
              scope: GLOBAL
              secret: ${JENKINS_KUBERNETES_TOKEN}
          - usernamePassword:
              description: wizard-github-token
              scope: GLOBAL
              id: wizard-github-token
              username: oauth2
              password: ${WIZARD_GITHUB_TOKEN}
jenkins:
  systemMessage: "Automated Jenkins Setup using Docker and Jenkins Configuration as Code"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${JENKINS_ADMIN_ID}
          password: ${JENKINS_ADMIN_PASSWORD}
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  agentProtocols:
    - "JNLP4-connect"
    - "Ping"
  clouds:
    - kubernetes:
        containerCap: 10
        containerCapStr: "10"
        credentialsId: "kubernetes-jenkins-token"
        # jenkinsUrl: http://${LOCAL_IP_ADDRESS}:8080
        jenkinsUrl: http://jenkins.scalastic.local:8080
        name: "kubernetes"
        namespace: "jenkins"
        serverUrl: "https://kubernetes.docker.internal:6443"
        skipTlsVerify: true
        webSocket: true
  labelAtoms:
    - name: "built-in"
    - name: "removed-master"
  labelString: "removed-master"
  markupFormatter: "plainText"
  mode: EXCLUSIVE
  myViewsTabBar: "standard"
  numExecutors: 0
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
jobs:
  - script: >
      pipelineJob('test-kubernetes-agent') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/scalastic/wizard.git')
                  credentials('wizard-github-token')
                }
                branch('*/14-redesign-gitlab-ci-platform-for-testing')
              }
            }
            lightweight()
          }
        }
      }
unclassified:
  location:
    # url: http://${LOCAL_IP_ADDRESS}:8080/
    url: http://jenkins.scalastic.local:8080/
  ansiColorBuildWrapper:
    globalColorMapName: "xterm"
