FROM alpine:latest

LABEL Author="wizard by scalastic"

# make sure the package repository is up to date
RUN set -ex \
    # Create a non-root user
    && addgroup --system --gid 1001 appgroup \
    && adduser --system --uid 1000 -G appgroup --shell /bin/bash appuser \
    # Upgrade the package index and install security upgrades
    && apk update \
    && apk upgrade \
    # Install bash and jq
    && apk add bash \
    && apk add jq \
    # Clean up 
    && rm -rf /var/lib/apt/lists/* \
    && rm -rf /var/cache/*/* \ 
    && echo "" > /root/.ash_history \
    && mkdir /app \
    && chown -R appuser:appgroup /app \
    # change default shell from ash to bash
    && sed -i -e "s/bin\/ash/bin\/bash/" /etc/passwd

ENV LC_ALL=en_US.UTF-8

# Set the user to run the application
USER appuser
WORKDIR /app