name: Test and Code Coverage
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
      - name: Install jq
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          command -v jq
      - name: Install kcov
        run: |
          sudo apt-get install -y kcov
      - name: Install shellspec
        run: |
          echo "${HOME}/.local/bin" >> "$GITHUB_PATH"
          curl -fsSL https://git.io/shellspec | sh -s master -y
          echo "--color" > $HOME/.shellspec
      - name: Generate coverage report
        run: |
          make all
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # required for private repos
          directory: coverage
          flags: unittests # optional
          name: codecov-wizard # optional
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
